enum BluetoothOperationCode {
  START_SCAN,
  STOP_SCAN,
  CONNECT,
  CLOSE_CONNECT,
  BLUETOOTH_LIST,
  READER,
  READER_DATA,
  SET_ANTENNA,
  SET_ANTENNA_POWER,
  QUERY_RFID_CAPACITY,
  INSTRUCTION_ERROR,
  OTHER_ERROR,
}