enum BluetoothFailedCode {
  NOT_SET_ANTENNA_NUM,
  READER_OPERATION_FAILED,
  NOT_APPEAR_OVER,
  SET_ANTENNA_NUM_FAILED,
  SET_ANTENNA_POWER_FAILED,
  QUERY_RFID_CAPACITY_FAILED,
  CONNECT_FAILED,
  NOT_SUPPORT_BLUETOOTH,
  BLUETOOTH_NOT_TURN_ON,
  PERMISSION_DENIED,
  ERROR_CODE,
}